package com.migia.OperationsHub.model.enums;

public enum Permission {
    VIEW_MEMBERS,
    INVITE_MEMBERS,
    REMOVE_MEMBERS,
    CHANGE_MEMBER_ROLE,
    VIEW_INVENTORY,
    MANAGE_INVENTORY,
    VIEW_ORDERS,
    MANAGE_ORDERS,
    VIEW_INVOICES,
    MANAGE_INVOICES,
    VIEW_PAYMENTS,
    MANAGE_PAYMENTS,
    VIEW_CUSTOMERS,
    MANAGE_CUSTOMERS,
    VIEW_PRODUCTS,
    MANAGE_PRODUCTS,
    MANAGE_ORGANIZATION_SETTINGS,
    MANAGE_EMPLOYEES,
    VIEW_EMPLOYEES,
    CREATE_ORDER,
    VIEW_OWN_ORDERS,
    MANAGE_ORGANIZATION
}
